name       : python-zope.interface
version    : 5.4.0
release    : 11
source     :
    - https://github.com/zopefoundation/zope.interface/archive/refs/tags/5.4.0.tar.gz : a1a9168135311439df4c682db56b5041983e5a2a33f8739200968e2c2badeb32
license    : ZPL-2.1
component  : programming.python
summary    : Python Zope Interface
description: |
    This package provides an implementation of “object interfaces” for Python. Interfaces are a mechanism for labeling objects as conforming to a given API or contract. So, this package can be considered as implementation of the Design By Contract methodology support in Python.
builddeps  :
    - pkgconfig(python3)
    - python-coverage
    - python-zope.event
    - python-zope.testing # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
