name       : python-zope.interface
version    : 4.1.3
release    : 1
source     :
    - https://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.1.3.tar.gz : 2e221a9eec7ccc58889a278ea13dcfed5ef939d80b07819a9a8b3cb1c681484f
license    : ZPL-2.1
summary    : Python Zope Interface
description: |
    This package provides an implementation of “object interfaces” for Python. Interfaces are a mechanism for labeling objects as conforming to a given API or contract. So, this package can be considered as implementation of the Design By Contract methodology support in Python.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
