name       : python-zope.interface
version    : 4.6.0
release    : 6
source     :
    - https://github.com/zopefoundation/zope.interface/archive/4.6.0.tar.gz : 1b653e63fc9d2fd61eec9ef3d486a415048e4e57e8efd68828aeb244d0948298
license    : ZPL-2.1
component  : programming.python
summary    : Python Zope Interface
description: |
    This package provides an implementation of “object interfaces” for Python. Interfaces are a mechanism for labeling objects as conforming to a given API or contract. So, this package can be considered as implementation of the Design By Contract methodology support in Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-zope.event
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
